import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { analyze } from '../src/analyzer.js';
import { human, sarif, shouldFail } from '../src/output.js';

function fixture(config, code = '') { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'review-guard-')); fs.writeFileSync(path.join(dir, 'shopify.app.toml'), config); fs.writeFileSync(path.join(dir, 'app.js'), code); return dir; }
test('reports missing compliance configuration and external listing checks', () => { const report = analyze(fixture('application_url = "https://example.test"\nembedded = true\n')); assert.ok(report.findings.some(f => f.ruleId === 'AR-COMPLIANCE-001')); assert.ok(report.findings.some(f => f.status === 'NEEDS_REVIEW')); assert.equal(report.toolVersion, '0.1.3'); });
test('recognizes compliance topics and webhook security signals', () => { const dir = fixture('application_url = "https://example.test"\n[webhooks]\napi_version = "2026-10"\n[[webhooks.subscriptions]]\nuri = "/webhooks"\ncompliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]\n', 'export function webhook(req) { const rawBody = req.rawBody; const signature = req.headers["X-Shopify-Hmac-SHA256"]; crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(signature)); const id = req.headers["X-Shopify-Webhook-Id"]; }'); const report = analyze(dir); assert.equal(report.findings.filter(f => f.ruleId === 'AR-COMPLIANCE-001').length, 0); assert.ok(!report.findings.some(f => f.ruleId === 'AR-WEBHOOK-001')); });
test('redacts secret values and produces valid SARIF shape', () => { const report = analyze(fixture('application_url = "http://localhost:3000"\n', 'const client_secret = "this-is-not-output-and-is-long";')); const json = JSON.stringify(report); assert.ok(!json.includes('this-is-not-output-and-is-long')); assert.equal(sarif(report).version, '2.1.0'); assert.equal(shouldFail(report, 'high'), true); });
test('detects committed .env files but does not print their values', () => { const dir = fixture('application_url = "https://example.test"\n'); fs.writeFileSync(path.join(dir, '.env'), 'SHOPIFY_API_SECRET=never-print-this-value\n'); const report = analyze(dir); assert.ok(report.findings.some(f => f.ruleId === 'AR-SECURITY-001')); assert.ok(!JSON.stringify(report).includes('never-print-this-value')); });
test('honors fail-on severity and strict review policy', () => { const dir = fixture('application_url = "https://example.test"\n[webhooks]\n[[webhooks.subscriptions]]\nuri = "/webhooks"\ncompliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]\n', 'app.post("/webhooks", express.json(), handler);'); const report = analyze(dir); assert.equal(shouldFail(report, 'high'), true); assert.equal(shouldFail(report, 'medium'), true); const embedded = analyze(fixture('application_url = "https://example.test"\nembedded = true\n[webhooks]\n[[webhooks.subscriptions]]\nuri = "/webhooks"\ncompliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]\n')); assert.equal(shouldFail(embedded, 'high'), false); assert.equal(shouldFail(embedded, 'high', true), true); });
test('supports explicit config selection and empty repositories', () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'review-empty-')); const empty = analyze(dir); assert.ok(empty.findings.some(f => f.ruleId === 'AR-CONFIG-001')); fs.writeFileSync(path.join(dir, 'shopify.app.dev.toml'), 'application_url = "http://localhost:3000"\n'); fs.writeFileSync(path.join(dir, 'shopify.app.toml'), 'application_url = "https://example.test"\n'); const selected = analyze(dir, { config: 'shopify.app.toml' }); assert.equal(selected.findings.some(f => f.ruleId === 'AR-CONFIG-003'), false); });
test('does not follow symlinks outside the repository', () => { const dir = fixture('application_url = "https://example.test"\n'); const outside = fs.mkdtempSync(path.join(os.tmpdir(), 'review-outside-')); fs.writeFileSync(path.join(outside, 'secret.js'), 'const client_secret = "outside-secret-value";'); try { fs.symlinkSync(outside, path.join(dir, 'linked')); } catch { return; } const report = analyze(dir); assert.ok(!JSON.stringify(report).includes('outside-secret-value')); });
test('human output contains stable status and remediation text', () => { const report = analyze(fixture('application_url = "https://example.test"\n')); const text = human(report); assert.match(text, /AR-COMPLIANCE-001/); assert.match(text, /Fix:/); });
